version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: mongoose
    depends_on:
      - mongo
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - server